name: Build Mac Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Inspect Xcode project
        run: |
          xcodebuild -list -project "Dorop/Builds/MacOSX/DoropEngine.xcodeproj"

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: mac-vst3
          path: "**/*.vst3"
